print("JF-Secure by Dab 2020")
print('Enter your Domain')
x = input()
print("Enter the adress of your Jellyfin Server e.g: Localhost:8096 ")
y = input()
fin = open("caddyfile", "rt")
data = fin.read()
data = data.replace('example.org', x)
data = data.replace('localhost:8096',y)
fin.close()
fin = open("caddyfile", "wt")
fin.write(data)
fin.close()